SRC=$(wildcard *.tex)
PNG=$(SRC:.tex=.png)

all: $(PNG)

%.pdf: %.tex
	latexmk --pdf $<

%.png: %.pdf
	convert -flatten -density 300 -trim $<[0] -quality 100 $@
	latexmk -c $<
	rm -f *.nav *.snm *.vrb
